### PR TITLE
FallbackProps as generic, so we can inject desired type without breaking change

### PR DESCRIPTION
**Pull request by enguerranws**
**What**: FallbackProps as a generic that has any default, instead of any

**Why**: I came across an issue where I'm using fallbackRender : its argument has an any type, so I could not use it with custom errors (e.g. returning an object) in JSX to fit (react/prop-types eslint rule).

Before: 
```
<ErrorBoundary
    fallbackRender={(props) => {
      return (
        <MainWrapper layout="default">
          <Alert
            severity="error"
            title="Erreur"
            description={props.error.message} // 'error' is missing in props validationeslint[react/prop-types](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/prop-types.md)
          />
        </MainWrapper>
      );
    }}
  >
    {children}
  </ErrorBoundary>
 ```

After: 
```
<ErrorBoundary
    fallbackRender={(props: FallbackProps<ClientError>) => {
      const { error } = props;
      return (
        <MainWrapper layout="default">
          <Alert
            severity="error"
            title="Erreur"
            description={error.message}
          />
        </MainWrapper>
      );
    }}
  >
    {children}
  </ErrorBoundary>
 ```

I guess we could go further and infer type, but this is a quick fix that doesn't break anything.

### CODE REVIEW

**Comment by bvaughn** [comment]
_Anything_ can be thrown inside of a React tree. Assuming the caught value would always be a specific type of error (or even an instance of `Error` at all) seems error prone. I can't accept this change because I think it would make the types misleading (which could cause other errors). The `any` type here was very intentional.

**Comment by enguerranws** [comment]
So, no way to let users use their own types, we just have to deal with an `any` arg? Or you want users to use typeguards on that argument?

**Comment by bvaughn** [comment]
> So, no way to let users use their own types, we just have to deal with an any arg

A thrown value can literally be anything in JavaScript, so yes, an `any` type is the correct type for this parameter. (This is why [TypeScript errors with TS1196](https://www.typescriptlang.org/play?#code/C4JwngBA3gUBEHoEwL4QMYENjoBYQAoBTEEAexAC4IBRUigSmjkQQgDpPUg) if you try to type the thrown value in a `catch` statement). An error boundary is essentially a try/catch around a set of React components which (in most cases) contain third party code references, which could (intentionally or unintentionally) throw an error.

**Comment by enguerranws** [comment]
Oh, you're right, I totally forgot about the unintentional errors that can be catched by this component. Sorry for that.

**Comment by bvaughn** [comment]
No worries!

**Pull request closed without merging**
