### PR TITLE
feat: add reset on re-render

### LINKED ISSUE #15: a friendlier default error component
react-error-overlay gives all sorts of nice details about the error.

A big red unhappy face lowers moral!

### LINKED ISSUE #26: Provide extra props to fallback component
I would like to pass extra props into the fallback component.

My use case:

``` tsx
const _Uploader = lazy(() => import('uploader'));

type Props = { onRequestClose: () => void };
const Uploader: SFC<Props> = props => (
  <ErrorBoundary FallbackComponent={MyErrorComponent}>
    <Suspense fallback={<MyLoadingComponent {...props} />}>
      <_Uploader {...props} />
    </Suspense>
  </ErrorBoundary>
);
```

I want my fallback component, `MyErrorComponent`, to receive the prop `onRequestClose`, in the same way I provide it to `MyLoadingComponent`.

Perhaps the fallback component should be provided as a render prop instead of as a `Component`?

``` tsx
props => <ErrorBoundary fallback={
  ({ error }) => <MyErrorComponent error={error} {...props} />
} />
```

### LINKED ISSUE #34: As (and recommend) fallback prop
Considering this is similar in spirit to Suspense, it would be nice if they share a similar more obvious API.

I really liked this code sample from Joe Savona's talk at react conf:

IMG_20191025_094055

Thoughts?

### PR DESCRIPTION
**Pull request by kentcdodds**
Closes #26 
Closes #15 
Closes #34 

BREAKING CHANGE: No longer support default FallbackComponent.
BREAKING CHANGE: Codebase is no longer written in Flow so flowtypes are no longer available (I am willing to add type defs if someone wants to do that though... Shouldn't be too difficult I expect. I just don't use flow).

### CODE REVIEW

**Comment by kentcdodds** [comment]
I can go ahead and merge this myself @bvaughn (I'd actually prefer to merge it so I can kick off the automatic releases properly). I just need permissions on TravisCI so I can get that set up.

**Comment by kentcdodds** [comment]
Kinda wondering whether this reset on re-render is a bad idea though 😬

**Comment by BurntCaramel** [comment]
It should at least be opt-in, rather than opt-out with `memo()`?

**Comment by kentcdodds** [comment]
FYI: I made a significant change. Rather than automatically resetting on props changes (which I've been convinced is a bad idea), we've exposed a mechanism for resetting the error state *and* allowing the developer to reset their own component state at the same time by exposing a `resetErrorBoundary` function and adding a `fallbackRender` render prop.

This is documented in the README and I'm ready to merge this when CI is passing.

**Comment by kentcdodds** [comment]
Looked through a few issues and added them to the list of things that this PR addresses.

**Pull request merged**
